LYMPHA_MODE=test
LYMPHA_INTERFACE=wlan0
LYMPHA_HTTP_PORTS="8080"
LYMPHA_EVE_PATH=suricata/logs/eve.json
LYMPHA_SURICATA_THRESHOLD=3
LYMPHA_SECUREBERT_THRESHOLD=2
LYMPHA_WINDOW_MINUTES=2
LYMPHA_SECUREBERT_MODEL=ehsanaghaei/SecureBERT
LYMPHA_SECUREBERT_SCORE_THRESHOLD=0.3
LYMPHA_DB_PATH=security.db
